bitcoind:
  type: union
  name: Bitcoin Core
  description: |
    The Bitcoin Core node to connect to:
      - internal: The Bitcoin Core or Proxy services installed to your Embassy
      - external: An unpruned Bitcoin Core node running on a different device
  tag:
    id: type
    name: Type
    variant-names:
      internal: Internal (Bitcoin Core)
      internal-proxy: Internal (Bitcoin Proxy)
      external: External
    description: |
      The Bitcoin Core node to connect to:
        - internal: The Bitcoin Core and Proxy services installed to your Embassy
        - external: An unpruned Bitcoin Core node running on a different device
  default: internal
  variants:
    internal:
      user:
        type: pointer
        name: RPC Username
        description: The username for Bitcoin Core's RPC interface
        subtype: package
        package-id: bitcoind
        target: config
        multi: false
        selector: "$.rpc.username"
      password:
        type: pointer
        name: RPC Password
        description: The password for Bitcoin Core's RPC interface
        subtype: package
        package-id: bitcoind
        target: config
        multi: false
        selector: "$.rpc.password"
    internal-proxy:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user allocated to electrs
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users[?(@.name == "electrs")].name'
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user allocated to electrs
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users[?(@.name == "electrs")].password'
    external:
      connection-settings:
        type: object
        name: Connection Settings
        description: Information to connect to an external unpruned Bitcoin Core node
        spec:
          rpc-host:
            type: string
            name: Public Address
            description: The public address of your Bitcoin Core server
            nullable: false
          rpc-user:
            type: string
            name: RPC Username
            description: The username for the RPC user on your Bitcoin Core RPC server
            nullable: false
          rpc-password:
            type: string
            name: RPC Password
            description: The password for the RPC user on your Bitcoin Core RPC server
            nullable: false
          rpc-port:
            type: number
            name: RPC Port
            description: The port that your Bitcoin Core RPC server is bound to
            nullable: false
            range: "[0,65535]"
            integral: true
            default: 8332
          p2p-host:
            type: string
            name: P2P Public Address
            description: The public address of your Bitcoin Core server's peer interface
            nullable: false
          p2p-port:
            type: number
            name: P2P Port
            description: The port on which your Bitcoin Core listens for p2p connections
            nullable: false
            range: "[0,65535]"
            integral: true
            default: 8333
log-filters:
  type: enum
  name: Log Filters
  values:
    - ERROR
    - WARN
    - INFO
    - DEBUG
    - TRACE
  value-names:
    ERROR: Error
    WARN: Warning
    INFO: Info
    DEBUG: Debug
    TRACE: Trace
  default: "INFO"
index-batch-size:
  type: number
  name: Index Batch Size
  description: |
    Maximum number of blocks to request from bitcoind per batch
  nullable: true
  range: "[1,10000]"
  integral: true
  units: blocks
index-lookup-limit:
  type: number
  name: Index Lookup Limit
  description: |
    Number of transactions to lookup before returning an error, to prevent 'too popular' addresses from causing the RPC server to get stuck (0 - disable the limit)"
  nullable: true
  range: "[1,10000]"
  integral: true
  units: transactions
